### PR TITLE
Perl 5 Project Idea, RPerl Operators

### PR DESCRIPTION
**Pull request by wbraswell**
Edit both files required for the new project idea

### CODE REVIEW

**Comment by JJ** [comment]
Thanks!

**Comment by patzim** [comment]
@wbraswell Isn't implementing one single operator too little work for someone working on it for three months?

**Comment by JJ** [comment]
@patzim from what I know from RPerl, it's not that easy and it involves a good amount of low-level C programming. Let's hear from him anyway.

**Comment by wbraswell** [comment]
@patzim
Yes @JJ is correct, it is not always easy to implement RPerl operators, which is why I have marked this project as "medium" difficulty.

As I have specified in the "Expected Outcomes" section of the document (emphasis added):

https://github.com/perl-gsoc-2019/ideas/blob/master/perl5/RPerl_Operators.md

> "We must implement **_at least one_** RPerl operator"

If we only implement one operator as part of this project, then we can consider it a success.  If we have time to implement more than one operator, then we can consider it an even greater success!  :-)

**Pull request merged**
