### PR TITLE
New idea: Pull Request Club

### PR DESCRIPTION
**Pull request by kyzn**

### CODE REVIEW

**Comment by patzim** [comment]
@kyzn Can I ask you to clarify the Expected Outcomes section? Currently the extent of the project is unclear and the success or failure of the project is hard to determine. It would be good to list more concrete milestones.

**Comment by kyzn** [comment]
@patzim @JJ 

This is my first time at GSoC, so maybe I was mistaken. Pull Request Club is a project that is already live, though it's in a early beta phase. I don't have any clear goals except making improvements & implementing new features. If that sounds like it's not fit for GSoC, I'd be happy to pull it back for this year and come back next year with some measurable goals.

**Comment by JJ** [comment]
@kyzn a measurable goal can be a milestone that you want to reach. Like, "Create a dashboard with PR statistics". "Add social networks bridge". "Make PR club multi-language". That's basically what @patzim means, and what Google would request.

**Comment by kyzn** [comment]
Thanks @JJ for examples. Do you think these look good?

- **Public stats:** Improve landing page to include some statistics such as "how many active assignments are there" and "how many assignments were completed".
- **Implement language-selection support:** Let users select programming languages that they want to work on.

**Comment by JJ** [comment]
@kyzn If that's OK for you, I think it's fine.

**Comment by kyzn** [comment]
@JJ awesome! I'll submit a PR soon.

**Comment by patzim** [comment]
@kyzn Just to be sure: The amount of work you propose should be suitable for a student to work on for three months. The expected outcomes should be measurable, so you as a mentor can determine whether the project was a success of failure during the project evaluation phase. See https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list.html for a more detailed explanation what a project idea should include. Also be sure you are willing to be a mentor, with respect to the [responsibility it entails](https://developers.google.com/open-source/gsoc/help/responsibilities#mentor_responsibilities).
It is great to see a perl using project in the ideas list and not only core stuff!

**Comment by kyzn** [comment]
@patzim @JJ 

Re-reading [responsibilities](https://developers.google.com/open-source/gsoc/help/responsibilities#mentor_responsibilities), "Respond to questions within 24 hours" sounds doable. But like [this page](https://google.github.io/gsocguides/mentor/notes-for-first-year-organizations.html) suggests, I don't think I will be able to consistently do 4-5 hour of work per week for 3 months, if project gets selected and I end up being the only mentor.

**Comment by kyzn** [comment]
I've just submitted https://github.com/perl-gsoc-2019/ideas/pull/24, will do my best 🙂

**Pull request merged**
