### PR TITLE
Add measureable goals for Pull Request Club

### PR DESCRIPTION
**Pull request by kyzn**

### CODE REVIEW

**Comment by kyzn** [comment]
@patzim @JJ Is this change enough to move this project out from list of incomplete proposals?

**Comment by JJ** [comment]
@kyzn We're very busy right now with the actual filling of the proposal... We'll check it out, probably after submission.

**Comment by kyzn** [comment]
Thanks, and good luck!

**Comment by patzim** [comment]
I added it back in.

**Pull request merged**
